name: Deploy Apps

on:
  push:
    branches:
    - main

jobs:
  deploy-admin:
    name: deploy admin app to s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: admin/
        run: yarn --frozen-lockfile
      - name: Build React app
        working-directory: admin/
        run: yarn build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        working-directory: admin/
        run: aws s3 sync admin/build s3://${{ secrets.ADMIN_S3_BUCKET_NAME }} --delete
  
  deploy-student:
    name: deploy student app to s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: student/
        run: yarn --frozen-lockfile
      - name: Build React app
        working-directory: student/
        run: yarn build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        working-directory: student/
        run: aws s3 sync student/build s3://${{ secrets.STUDENT_S3_BUCKET_NAME }} --delete
  
  deploy-server:
    name: deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build and deploy
      - name: sam build
        working-directory: server-rust/
        run: sam build --use-container
      - name: sam deploy
        working-directory: server-rust/
        run: sam deploy